name: CI Pipeline - Sonar

on:
#  push:
#    branches: [ main ]
    
#  pull_request:
#    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
      sonar:
        type: string
  
jobs:
  build:

    runs-on: [ nsll-de ]

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup .NET & Build
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet build SG-Clicker.sln
   
  #  - name: SonarQube Scan
  #    uses: sonarsource/sonarqube-scan-action@master
  #    env:
  #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
  #  - run: docker build . --file Dockerfile

  #  - name: Upload Artifact to GitHub Package
  #    uses: actions/upload-artifact@v2
  #    with: 
  #      name: web-app-image
  #      path: /app/publish

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: nirosans/sg-clicker
  
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
